server:
  port: 30000
spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1
    alicloud:
      access-key: LTAI4FdB2ys7y4ErfG89ZDbw
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: gulimall-upload

